version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      electron:
        patterns: ['electron', 'electron-*', '@electron/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
